---
- name: Copy systemd unit file
  ansible.builtin.copy:
    src: docker-container.service
    dest: /etc/systemd/system/
    
- name: Make sure config path exist
  ansible.builtin.file:
    path: /etc/systemd/system/docker-container.service.d
    owner: root
    group: root
    mode: "0644"
    state: directory

- name: Copy config file
  ansible.builtin.copy:
    src: docker-container.conf
    dest: /etc/systemd/system/docker-container.service.d/